[tool.ruff]

extend-select = ["C4", "SIM", "TCH", "W", "I", "UP", "S", "B", "ISC", "ICN", "G", "PT", "Q", "RET", "TID", "RUF", "ANN"]
#"ANN" , "T20" - for release , -ARG? , ERA - for relese, PTH - but i'm lazy

# Ignore the following linter problems:
# * ANN101 Missing type annotation for self in method -> I won't annotate self
# * ANN401 Dynamically typed expressions (typing.Any) are disallowed in `*args|**krawgs` -> I need it in wrapper
# * F821 Undefined name ClassName -> I use forward declaration due to circular import, yeah
ignore = ["ANN101", "ANN401", "F821"]

show-fixes = true
line-length = 120

[tool.ruff.extend-per-file-ignores]
"test_*" = ["S101"]